// src/styles.js

export const C = {
  green: "#4a8c1c",
  greenLight: "#6bb832",
  pink: "#d4848a",
  pinkLight: "#f0b8bc",
  cream: "#FFFCF6",
  creamDark: "#F5EFE0",
  text: "#2d2d2d",
  muted: "#888",
};

export const adminStyles = {
  label: {
    fontSize: 14,
    fontWeight: "bold",
    color: C.text,
    marginBottom: 6,
    display: "block",
    marginTop: 14,
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 12,
    border: `2px solid ${C.creamDark}`,
    background: C.cream,
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    color: C.text,
  },
};

export const styles = {
  root: {
    minHeight: "100vh",
    background: C.cream,
    color: C.text,
    // 🔥 CORREÇÃO MOBILE: Impede o site de vazar pelas laterais
    overflowX: "hidden",
    width: "100%",
  },
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px", // 🔥 Ajustado para ecrãs menores
    transition: "background 0.3s, box-shadow 0.3s",
    // 🔥 CORREÇÃO MOBILE: Permite que o menu desça de linha se não couber
    flexWrap: "wrap",
    gap: "10px",
  },
  navLogo: { display: "flex", alignItems: "center", gap: 8 },
  logoCircle: { fontSize: 28 },
  logoText: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 900,
    color: C.green,
  },
  logoSub: { fontSize: 11, color: C.pink, fontWeight: 600, letterSpacing: 0.5 },
  cartBtn: {
    position: "relative",
    background: C.green,
    border: "none",
    borderRadius: 50,
    width: 44,
    height: 44,
    fontSize: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 14px rgba(74,140,28,0.3)",
  },
  badge: {
    position: "absolute",
    top: -6,
    right: -6,
    background: C.pink,
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 50,
    width: 20,
    height: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  hero: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center", // 🔥 Mantém centralizado no telemóvel
    padding: "120px 20px 60px", // 🔥 Mais espaço no topo caso o nav fique com 2 linhas
    background: `linear-gradient(135deg, ${C.cream} 55%, ${C.creamDark} 100%)`,
    position: "relative",
    overflow: "hidden",
    gap: 40,
    flexWrap: "wrap", // 🔥 CORREÇÃO MOBILE: Permite a arte descer para baixo do texto
  },
  heroInner: {
    flex: 1,
    maxWidth: 560,
    minWidth: 280,
    animation: "fadeInUp 0.8s ease both",
  },
  heroTag: {
    display: "inline-block",
    background: C.pinkLight,
    color: C.pink,
    borderRadius: 20,
    padding: "6px 16px",
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 20,
  },
  heroTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "clamp(36px, 6vw, 68px)",
    lineHeight: 1.1,
    color: C.text,
    marginBottom: 20,
  },
  heroAccent: { color: C.green },
  heroDesc: {
    fontSize: 17,
    color: C.muted,
    lineHeight: 1.7,
    marginBottom: 32,
    maxWidth: 440,
  },
  heroBtn: {
    display: "inline-block",
    background: C.green,
    color: "#fff",
    padding: "14px 32px",
    borderRadius: 50,
    fontWeight: 700,
    fontSize: 16,
    textDecoration: "none",
    boxShadow: "0 6px 24px rgba(74,140,28,0.35)",
  },
  heroDeco: { flex: 1, position: "relative", minHeight: 300, minWidth: 280 },
  decoCircle1: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: "50%",
    background: `radial-gradient(circle, ${C.pinkLight}55, transparent 70%)`,
    top: "10%",
    left: "20%",
  },
  decoCircle2: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: "50%",
    background: `radial-gradient(circle, rgba(107,184,50,0.2), transparent 70%)`,
    bottom: "10%",
    right: "10%",
  },
  decoEmojis: { position: "absolute", inset: 0 },
  floatEmoji: {
    position: "absolute",
    fontSize: 40,
    animation: "float 3s ease-in-out infinite",
  },
  bens: {
    display: "flex",
    flexWrap: "wrap",
    gap: 20,
    padding: "60px 20px",
    background: C.creamDark,
    justifyContent: "center",
  },
  benCard: {
    background: "#fff",
    borderRadius: 20,
    padding: "28px 24px",
    flex: "1 1 200px",
    maxWidth: 240,
    textAlign: "center",
    boxShadow: "0 2px 16px rgba(0,0,0,0.06)",
  },
  benIco: { fontSize: 36, display: "block", marginBottom: 10 },
  benTitle: { fontSize: 15, color: C.green, display: "block", marginBottom: 6 },
  benDesc: { fontSize: 13, color: C.muted, lineHeight: 1.5 },
  menu: { padding: "80px 20px", maxWidth: 1200, margin: "0 auto" },
  menuHeader: { textAlign: "center", marginBottom: 48 },
  menuTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "clamp(28px, 4vw, 44px)",
    color: C.text,
    marginBottom: 10,
  },
  menuSub: { fontSize: 16, color: C.muted },
  grid: {
    display: "grid",
    // 🔥 CORREÇÃO MOBILE: Reduzido de 300px para 280px para caber em telas menores
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 28,
  },
  card: {
    background: "#fff",
    borderRadius: 24,
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0,0,0,0.07)",
  },
  cardEmoji: {
    fontSize: 72,
    textAlign: "center",
    padding: "32px 20px 16px",
    background: `linear-gradient(180deg, ${C.creamDark} 0%, #fff 100%)`,
    lineHeight: 1,
  },
  cardBody: { padding: "16px 24px 24px" },
  cardName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 18,
    color: C.text,
    marginBottom: 8,
  },
  cardDesc: { fontSize: 13, color: C.muted, lineHeight: 1.6, marginBottom: 16 },
  tamRow: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 20 },
  tamBtn: {
    padding: "6px 14px",
    borderRadius: 20,
    border: `2px solid ${C.creamDark}`,
    background: C.creamDark,
    color: C.muted,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  tamBtnActive: {
    border: `2px solid ${C.green}`,
    background: C.green,
    color: "#fff",
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  preco: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    color: C.green,
    fontWeight: 700,
  },
  addBtn: {
    background: C.pink,
    color: "#fff",
    border: "none",
    borderRadius: 50,
    padding: "10px 20px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(212,132,138,0.4)",
  },
  footer: {
    background: C.text,
    color: "#fff",
    textAlign: "center",
    padding: "48px 20px",
  },
  footerLogo: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 28,
    color: C.greenLight,
    display: "block",
    marginBottom: 8,
  },
  footerSub: { color: "#aaa", fontSize: 14, marginBottom: 8 },
  footerCopy: { color: "#555", fontSize: 12 },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    zIndex: 200,
    transition: "opacity 0.3s",
  },
  sidebar: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: "100%", // 🔥 CORREÇÃO MOBILE: Ocupa 100% no telemóvel
    maxWidth: 380, // 🔥 Mas limita a 380px no PC
    background: "#fff",
    zIndex: 201,
    boxShadow: "-8px 0 40px rgba(0,0,0,0.15)",
    transition: "transform 0.35s cubic-bezier(0.4,0,0.2,1)",
    display: "flex",
    flexDirection: "column",
  },
  sideHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "24px",
    borderBottom: `2px solid ${C.creamDark}`,
  },
  sideTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    color: C.text,
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: 20,
    cursor: "pointer",
    color: C.muted,
  },
  emptyCart: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    color: C.muted,
    textAlign: "center",
    padding: 32,
  },
  cartItems: { flex: 1, overflowY: "auto", padding: "16px 24px" },
  cartItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 0",
    borderBottom: `1px solid ${C.creamDark}`,
  },
  cartEmoji: { fontSize: 28, flexShrink: 0 },
  cartInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 2 },
  cartName: { fontSize: 14, color: C.text },
  cartTam: { fontSize: 12, color: C.muted },
  cartQtd: { display: "flex", alignItems: "center", gap: 8 },
  qtdBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: `1px solid ${C.creamDark}`,
    background: C.creamDark,
    cursor: "pointer",
    fontSize: 16,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  qtdNum: { fontSize: 15, fontWeight: 700, minWidth: 20, textAlign: "center" },
  cartPreco: { fontSize: 15, fontWeight: 700, color: C.green, flexShrink: 0 },
  cartFooter: { padding: "20px 24px", borderTop: `2px solid ${C.creamDark}` },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  totalLabel: { fontSize: 16, fontWeight: 700, color: C.text },
  totalVal: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 24,
    color: C.green,
    fontWeight: 700,
  },
  whatsBtn: {
    width: "100%",
    background: "#25D366",
    color: "#fff",
    border: "none",
    borderRadius: 16,
    padding: "16px",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 6px 20px rgba(37,211,102,0.4)",
    marginBottom: 10,
  },
  cartNote: { fontSize: 11, color: C.muted, textAlign: "center" },
  toast: {
    position: "fixed",
    bottom: 32,
    left: "50%",
    transform: "translateX(-50%)",
    background: C.green,
    color: "#fff",
    padding: "14px 28px",
    borderRadius: 50,
    fontSize: 15,
    fontWeight: 600,
    boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
    zIndex: 300,
    animation: "slideIn 0.4s ease both",
  },
};
